services:
  - type: web
    name: nestjs-backend
    env: node
    plan: free  # You can use 'starter' or other plans if needed
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value:"mongodb+srv://shawil:Shawil12!@cluster0.evltfnk.mongodb.net/fjuSongs?retryWrites=true&w=majority&appName=Cluster0"
